# Generated by Django 3.0.3 on 2023-07-12 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('taxa_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('genus', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'organisms',
            },
        ),
        migrations.CreateModel(
            name='PfamDescriptions',
            fields=[
                ('domain_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('domain_description', models.TextField()),
            ],
            options={
                'db_table': 'pfam_descriptions',
            },
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('protein_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('clade', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
                ('length', models.IntegerField()),
                ('taxa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proteins', to='biowebapp.Organism')),
            ],
            options={
                'db_table': 'proteins',
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField()),
                ('protein', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sequence', to='biowebapp.Protein')),
            ],
            options={
                'db_table': 'sequences',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biowebapp.PfamDescriptions')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='biowebapp.Protein')),
            ],
            options={
                'db_table': 'domains',
            },
        ),
    ]
