# Generated by Django 3.0.3 on 2023-07-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biowebapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
