# Generated by Django 3.0.3 on 2023-07-13 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biowebapp', '0003_auto_20230713_2010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PfamDescriptions',
            new_name='PfamDescription',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='domain',
            new_name='domain_id',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='protein',
            new_name='protein_id',
        ),
        migrations.RenameField(
            model_name='protein',
            old_name='taxa',
            new_name='taxa_id',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='protein_id',
            new_name='protein',
        ),
    ]
