# Generated by Django 3.0.3 on 2023-07-13 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biowebapp', '0004_auto_20230713_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='domain_id',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='protein_id',
        ),
        migrations.AddField(
            model_name='domain',
            name='domain',
            field=models.ForeignKey(db_column='domain_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='biowebapp.PfamDescription'),
        ),
        migrations.AddField(
            model_name='domain',
            name='protein',
            field=models.ForeignKey(db_column='protein_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='biowebapp.Protein'),
        ),
    ]
