# Generated by Django 3.0.3 on 2023-07-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biowebapp', '0005_auto_20230713_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protein',
            old_name='taxa_id',
            new_name='taxa',
        ),
    ]
